### ISSUE TITLE
location error！

### ISSUE THREAD

**Issue by xkungfu** [linzhiming0826/sanic-restful#6]
server run on port 8000, not 5000.

**Comment by xkungfu** [comment]
**curl http://localhost:8000/todos -d "task=something new" -X POST -v**

```

[2021-02-16 00:29:26 +0800] [1940] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2021-02-16 00:29:26 +0800] [1940] [INFO] Starting worker [1940]

[2021-02-16 00:29:32 +0800] [1940] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/todos'

Traceback (most recent call last):
  File "E:\PythonWork\env\lib\site-packages\sanic\app.py", line 914, in handle_request
    response = await response
  File "E:\PythonWork\env\lib\site-packages\sanic_restful_api\__init__.py", line 141, in wrapper
    resp = await resource(request, *args, **kwargs)
  File "E:\PythonWork\env\lib\site-packages\sanic_restful_api\__init__.py", line 293, in dispatch_request
    resp = await meth(request, *args, **kwargs)
TypeError: post() takes 1 positional argument but 2 were given

[2021-02-16 00:29:32 +0800] - (sanic.access)[INFO][127.0.0.1:49950]: POST http://localhost:8000/todos  500 1829

```

**Comment by xkungfu** [comment]
curl http://localhost:8000/todos -d "task=something new" -X POST -v



```

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:8000...
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /todos HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.75.0
> Accept: */*
> Content-Length: 18
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Length: 673
< Content-Type: text/html; charset=utf-8
< Connection: keep-alive
< Keep-Alive: 5
<
<!DOCTYPE html><html lang=en><meta charset=UTF-8><title>⚠️ 400 — Bad Request</title>
<style>
        html { font-family: sans-serif }
        h2 { color: #888; }
        .tb-wrapper p { margin: 0 }
        .frame-border { margin: 1rem }
        .frame-line > * { padding: 0.3rem 0.6rem }
        .frame-line { margin-bottom: 0.3rem }
        .frame-code { font-size: 16px; padding-left: 4ch }
        .tb-wrapper { border: 1px solid #eee }
        .tb-header { background: #eee; padding: 0.3rem; font-weight: bold }
        .frame-descriptor { background: #e2eafb; font-size: 14px }
    </style>
<h1>⚠️ 400 — Bad Request</h1><p>Failed when parsing body as json
* Connection #0 to host localhost left intact

```

**Comment by xkungfu** [comment]
curl http://localhost:8000/todos -d "{\"task\": \"somethin new\"}" -v
```

*   Trying ::1:8000...
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /todos HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.75.0
> Accept: */*
> Content-Length: 24
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Content-type: application/json
< Content-Length: 20
< Connection: keep-alive
< Keep-Alive: 5
<
{
    "task": "s"
}
* Connection #0 to host localhost left intact
```


finally worked. but what is "s"? why "something new" was changed to "s"?

**Comment by linzhiming0826** [comment]
parser.add_argument('task', location='files')

you can try it ，if not set location，code will update values form ('json', 'form', 'args', 'files')，finally the result is s

**Comment by xkungfu** [comment]
thanks.
